confirm_event:
  types:
    - id: unrostered
      name: Unrostered
      description: "Unrostered event"
    - id: sixes
      name: Sixes
      description: "Rostered Sixes match"
    - id: highlander
      name: Highlander
      description: "Rostered Highlander match"
  fields:
    - id: type
      emoji: ":card_box:"
      label: Type
      bold: true
    - id: day
      emoji: ":calendar_spiral:"
      label: Day
      bold: true
    - id: time
      emoji: ":alarm_clock:"
      label: Time
      bold: true
    - id: who
      emoji: ":busts_in_silhouette:"
      label: Who
    - id: maps
      include_types:
        - sixes
        - highlander
      emoji: ":map:"
      label: Maps
      bold: true
    - id: roster_sixes
      include_types:
        - sixes
      emoji: ":video_game:"
      label: Roster
      bold: true
      subfields:
        - id: combo_scout
          emote: <:tf_scout:1384378124036210718>
          label: Combo Scout
          bold: false
        - id: flank_scout
          emote: <:tf_scout:1384378124036210718>
          label: Flank Scout
          bold: false
        - id: pocket_soldier
          emote: <:tf_soldier:1384378104654594178>
          label: Pocket Soldier
          bold: false
        - id: roamer_soldier
          emote: <:tf_soldier:1384378104654594178>
          label: Roamer Soldier
          bold: false
        - id: demoman
          emote: <:tf_demoman:1384378186460037250>
          label: Demoman
          bold: false
        - id: medic
          emote: <:tf_medic:1384378148052926526>
          label: Medic
          bold: false
    - id: roster_highlander
      include_types:
        - highlander
      emoji: ":video_game:"
      label: Roster
      bold: true
      subfields:
        - id: scout
          emote: <:tf_scout:1384378124036210718>
          label: Scout
          bold: false
        - id: soldier
          emote: <:tf_soldier:1384378104654594178>
          label: Soldier
          bold: false
        - id: pyro
          emote: <:tf_pyro:1384377621684551781>
          label: Pyro
          bold: false
        - id: demoman
          emote: <:tf_demoman:1384378186460037250>
          label: Demoman
          bold: false
        - id: heavy
          emote: <:tf_heavy:1384377601761480714>
          label: Heavy
          bold: false
        - id: engineer
          emote: <:tf_engineer:1384377574733643848>
          label: Engineer
          bold: false
        - id: medic
          emote: <:tf_medic:1384378148052926526>
          label: Medic
          bold: false
        - id: sniper
          emote: <:tf_sniper:1384377638549983233>
          label: Sniper
          bold: false
        - id: spy
          emote: <:tf_spy:1384377657839321138>
          label: Spy
          bold: false
  reactions:
    - emoji: ":white_check_mark:"
    - emoji: ":x:"
  footer: "*React with :white_check_mark: if you can make it*"
availability_poll:
  header: "*Polling availability*\nReact with **all** of the days during which you are available **for at least an hour** between 6pm – 10pm."
